### ISSUE TITLE
Abnormal Scorer with Laion Aesthetic Predictor

### ISSUE THREAD

**Issue by hanwenxu1** [Enderfga/HumanRefiner#2]
When I use the Laion Aesthetic Predictor to get the abnormal scorer,  I found that it need images and rates to train. But in the HumanRefiner dataset, there is no rates. I wonder know that how to train the predictor without rates. 

Thanks for your help!

**Comment by Enderfga** [comment]
We used the number of abnormal target detection boxes as the score

**Comment by hanwenxu1** [comment]
I get it. Thank you for your so quick expain!
